[project]
name = 'Blockchain-Enabled-Indigenous-Knowledge-Preservation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-control]
path = 'contracts/access-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.attibution]
path = 'contracts/attibution.clar'
clarity_version = 2
epoch = 2.5

[contracts.benefits-sharing]
path = 'contracts/benefits-sharing.clar'
clarity_version = 2
epoch = 2.5

[contracts.knowledge-registration]
path = 'contracts/knowledge-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
